# File: carcontroller.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: carcontroller.py.1shot.das

'__pyarmor_enter_41422__(...)'
import numpy as np
from opendbc.car import Bus, structs
from opendbc.car.lateral import apply_std_steer_angle_limits
from opendbc.car.interfaces import CarControllerBase
from opendbc.car.changan import changancan
from opendbc.car.changan.values import CarControllerParams, CAR
from opendbc.can.packer import CANPacker
from opendbc.car.common.conversions import Conversions as CV
SteerControlType = structs.CarParams.SteerControlType
VisualAlert = structs.CarControl.HUDControl.VisualAlert

class CarController(CarControllerBase):
    '__pyarmor_enter_41425__(...)'
    
    def __init__(self, dbc_names, CP):
        '__pyarmor_enter_41428__(...)'
    # WARNING: Decompyle incomplete

    
    def update(self, CC, CS, now_nanos):
        '__pyarmor_enter_41431__(...)'
        _var_var_0 = CC.actuators
        _var_var_1 = CC.hudControl
        if self.first_start:
            self.counter_244 = CS.counter_244
            self.counter_1ba = CS.counter_1ba
            self.counter_17e = CS.counter_17e
            self.counter_307 = CS.counter_307
            self.counter_31a = CS.counter_31a
            self.first_start = False
        _var_var_2 = []
        self.counter_1ba = int(self.counter_1ba + 1) & 15
        self.counter_17e = int(self.counter_17e + 1) & 15
        if not CC.latActive and CS.steeringPressed:
            _var_var_3 = _var_var_0.steeringAngleDeg + CS.out.steeringAngleOffsetDeg
            _var_var_3 = apply_std_steer_angle_limits(_var_var_3, self.last_angle, CS.out.vEgoRaw, CS.out.steeringAngleDeg + CS.out.steeringAngleOffsetDeg, CC.latActive, self.params.ANGLE_LIMITS)
            _var_var_3 = np.clip(_var_var_3, CS.out.steeringAngleDeg - 7, CS.out.steeringAngleDeg + 7)
            _var_var_2.append(changancan.create_1BA_command(self.packer, CS.sigs1ba, _var_var_3, 1, self.counter_1ba))
        else:
            _var_var_3 = CS.out.steeringAngleDeg
            _var_var_2.append(changancan.create_1BA_command(self.packer, CS.sigs1ba, _var_var_3, 0, self.counter_1ba))
        self.last_angle = _var_var_3
        _var_var_2.append(changancan.create_17E_command(self.packer, CS.sigs17e, CC.longActive, self.counter_17e))
        if self.frame % 2 == 0:
            _var_var_4 = -5000
            _var_var_5 = np.clip(_var_var_0.accel, self.params.ACCEL_MIN, self.params.ACCEL_MAX)
            if _var_var_5 < 0:
                self.expected_daccel = _var_var_5
                self.actual_daccel_filtered = 0.9 * self.actual_daccel_filtered + 0.1 * CS.out.aEgo
                if self.actual_daccel_filtered > self.expected_daccel * 0.8:
                    self.slope_daccel = 0.15
                else:
                    self.slope_daccel = 0
                _var_var_5 -= self.slope_daccel
                _var_var_5 = np.clip(_var_var_5, self.last_apply_accel - 0.2, self.last_apply_accel + 0.1)
                if self.last_apply_accel >= 0 and _var_var_1.leadVisible and _var_var_1.leadDistanceBars < 30:
                    _var_var_5 = -0.4
                _var_var_5 = max(_var_var_5, -3.5)
                if CS.out.vEgoRaw * CV.MS_TO_KPH == 0 and self.last_speed > 0 and _var_var_1.leadVisible and _var_var_1.leadDistanceBars > 0:
                    self.stop_lead_distance = _var_var_1.leadDistanceBars
                if self.stop_lead_distance != 0 and CS.out.vEgoRaw * CV.MS_TO_KPH == 0 and self.last_speed == 0 and _var_var_1.leadVisible and _var_var_1.leadDistanceBars - self.stop_lead_distance > 1:
                    _var_var_5 = 0.5
            if CS.out.vEgoRaw * CV.MS_TO_KPH > 0:
                self.stop_lead_distance = 0
            if _var_var_5 > 0:
                _var_var_6 = CS.out.vEgoRaw * CV.MS_TO_KPH
                if _var_var_6 > 110:
                    (_var_var_7, _var_var_8) = (1100, 150)
                elif _var_var_6 > 90:
                    (_var_var_7, _var_var_8) = (800, 120)
                elif _var_var_6 > 70:
                    (_var_var_7, _var_var_8) = (800, 100)
                elif _var_var_6 > 50:
                    (_var_var_7, _var_var_8) = (800, 80)
                elif _var_var_6 > 10:
                    (_var_var_7, _var_var_8) = (500, 50)
                else:
                    (_var_var_7, _var_var_8) = (400, 50)
                _var_var_9 = _var_var_7 + int(abs(_var_var_5) / 0.05) * _var_var_8 - 5000
                self.expected_accel = _var_var_5
                self.actual_accel_filtered = 0.9 * self.actual_accel_filtered + 0.1 * CS.out.aEgo
                _var_var_9 += self.slope_compensation
                _var_var_9 = min(_var_var_9, -10)
                _var_var_4 = np.clip(_var_var_9, self.last_acctrq - 300, self.last_acctrq + 100)
            self.last_speed = CS.out.vEgoRaw * CV.MS_TO_KPH
            _var_var_5 = int(_var_var_5 / 0.05) * 0.05
            self.counter_244 = int(self.counter_244 + 1) & 15
            if self.CP.carFingerprint == CAR.QIYUAN_A05:
                _var_var_2.append(changancan.create_244_command_a05(self.packer, _var_var_5, self.counter_244, CC.longActive, _var_var_4))
            elif self.CP.carFingerprint == CAR.CHANGAN_Z6_IDD:
                _var_var_2.append(changancan.create_244_command_idd(self.packer, CS.sigs244, _var_var_5, self.counter_244, CC.longActive, _var_var_4, CS.out.vEgoRaw))
            else:
                _var_var_2.append(changancan.create_244_command(self.packer, CS.sigs244, _var_var_5, self.counter_244, CC.longActive, _var_var_4, CS.out.vEgoRaw))
            self.last_apply_accel = _var_var_5
            self.last_acctrq = _var_var_4
        if self.frame % 10 == 0:
            self.counter_307 = int(self.counter_307 + 1) & 15
            self.counter_31a = int(self.counter_31a + 1) & 15
            _var_var_2.append(changancan.create_307_command(self.packer, CS.sigs307, self.counter_307, CS.out.cruiseState.speedCluster * CV.MS_TO_KPH))
            _var_var_2.append(changancan.create_31A_command(self.packer, CS.sigs31a, self.counter_31a, CC.longActive, CS.steeringPressed))
        _var_var_10 = _var_var_0.as_builder()
        _var_var_10.steeringAngleDeg = float(self.last_angle)
        _var_var_10.accel = float(self.last_apply_accel)
        return (_var_var_10, _var_var_2)
        None if self.actual_accel_filtered < self.expected_accel * 0.4 else self, self.slope_compensation += 10, .slope_compensation(self, self.frame += 1, .frame)
        return None
        '__pyarmor_exit_41432__(...)'
        '__pyarmor_exit_41432__(...)'

    __classcell__ = None
    return None
    __classcell__ = None
    return None
    '__pyarmor_exit_41426__(...)'
    '__pyarmor_exit_41426__(...)'

return None
return None
'__pyarmor_exit_41423__(...)'
'__pyarmor_exit_41423__(...)'
