# File: carstate.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: carstate.py.1shot.das

'__pyarmor_enter_41365__(...)'
import copy
import time
from opendbc.car.common.conversions import Conversions as CV
from openpilot.common.filter_simple import FirstOrderFilter
from openpilot.common.realtime import DT_CTRL
from opendbc.can import CANDefine, CANParser
from opendbc.car.interfaces import CarStateBase
from opendbc.car.changan.values import CAR, DBC, STEER_THRESHOLD, EPS_SCALE
from opendbc.car import Bus, structs
SteerControlType = structs.CarParams.SteerControlType
TEMP_STEER_FAULTS = (0, 9, 11, 21, 25)
PERM_STEER_FAULTS = (3, 17)

class CarState(CarStateBase):
    '__pyarmor_enter_41368__(...)'
    
    def __init__(self, CP):
        '__pyarmor_enter_41371__(...)'
    # WARNING: Decompyle incomplete

    
    def update(self, can_parsers):
        '__pyarmor_enter_41374__(...)'
        _var_var_1 = can_parsers[Bus.pt]
        _var_var_2 = can_parsers[Bus.cam]
        _var_var_3 = structs.CarState()
        _var_var_3.doorOpen = any([
            _var_var_1.vl['GW_28B']['BCM_DriverDoorStatus']])
        _var_var_3.seatbeltUnlatched = _var_var_1.vl['GW_50']['SRS_DriverBuckleSwitchStatus'] == 1
        _var_var_3.parkingBrake = False
        if self.CP.carFingerprint == CAR.CHANGAN_Z6_IDD:
            _var_var_4 = _var_var_1.vl['GW_17A']['ESP_VehicleSpeed']
        elif self.CP.carFingerprint == CAR.QIYUAN_A07:
            _var_var_4 = _var_var_1.vl['GW_1C2']['ESP_VehicleSpeed']
        else:
            _var_var_4 = _var_var_1.vl['GW_187']['ESP_VehicleSpeed']
        _var_var_5 = _var_var_4 if _var_var_4 <= 5 else _var_var_4 / 0.98 + 2
        _var_var_3.vEgoRaw = _var_var_5 * CV.KPH_TO_MS
        (_var_var_3.vEgo, _var_var_3.aEgo) = self.update_speed_kf(_var_var_3.vEgoRaw)
        _var_var_3.vEgoCluster = _var_var_3.vEgo
        _var_var_3.standstill = abs(_var_var_3.vEgoRaw) < 0.001
        _var_var_3.steeringAngleOffsetDeg = 0
        _var_var_3.steeringAngleDeg = _var_var_1.vl['GW_180']['SAS_SteeringAngle']
        _var_var_3.steeringRateDeg = _var_var_1.vl['GW_180']['SAS_SteeringAngleSpeed']
        if self.CP.carFingerprint == CAR.QIYUAN_A05:
            _var_var_6 = int(_var_var_1.vl['GW_331']['TCU_GearForDisplay'])
            _var_var_3.brakePressed = _var_var_1.vl['GW_17D']['PCU_BrkPedlSts'] != 0
            _var_var_3.gasPressed = _var_var_1.vl['GW_17D']['PCU_RealAccPedl'] != 0
            self.steeringPressedMax = 1.5
            self.steeringPressedMin = 0.5
            if not _var_var_1.vl['GW_2A4']['LCDAR_Left_BSD_LCAAlert'] == 1:
                _var_var_1.vl['GW_2A4']['LCDAR_Left_BSD_LCAAlert'] == 1
            _var_var_3.leftBlindspot = _var_var_1.vl['GW_2A4']['LCDAR_Left_BSD_LCAAlert'] == 2
            if not _var_var_1.vl['GW_2A4']['LCDAR_BSD_LCAAlert'] == 1:
                _var_var_1.vl['GW_2A4']['LCDAR_BSD_LCAAlert'] == 1
            _var_var_3.rightBlindspot = _var_var_1.vl['GW_2A4']['LCDAR_BSD_LCAAlert'] == 2
        elif self.CP.carFingerprint == CAR.QIYUAN_A07:
            _var_var_3.brakePressed = False
            _var_var_3.gasPressed = _var_var_1.vl['GW_161']['EMS_RealAccPedal'] != 0
            self.steeringPressedMax = 1.5
            self.steeringPressedMin = 0.5
            _var_var_3.leftBlindspot = False
            _var_var_3.rightBlindspot = False
        elif self.CP.carFingerprint == CAR.CHANGAN_Z6_IDD:
            _var_var_6 = int(_var_var_1.vl['GW_338']['TCU_GearForDisplay'])
            _var_var_3.brakePressed = _var_var_1.vl['GW_1A6']['EMS_BrakePedalStatus'] != 0
            _var_var_3.gasPressed = _var_var_1.vl['GW_1C6']['EMS_RealAccPedal'] != 0
            self.steeringPressedMin = 1
            self.steeringPressedMax = 3
            _var_var_3.leftBlindspot = False
            _var_var_3.rightBlindspot = False
        else:
            _var_var_6 = int(_var_var_1.vl['GW_338']['TCU_GearForDisplay'])
            _var_var_3.brakePressed = _var_var_1.vl['GW_196']['EMS_BrakePedalStatus'] != 0
            _var_var_3.gasPressed = _var_var_1.vl['GW_196']['EMS_RealAccPedal'] != 0
            self.steeringPressedMin = 1
            self.steeringPressedMax = 6
            _var_var_3.leftBlindspot = False
            _var_var_3.rightBlindspot = False
        if self.CP.carFingerprint == CAR.QIYUAN_A07:
            _var_var_3.gearShifter = structs.CarState.GearShifter.drive
    # WARNING: Decompyle incomplete

    get_can_parsers = (lambda CP: '__pyarmor_enter_41377__(...)'{
Bus.cam: CANParser(DBC[CP.carFingerprint][Bus.pt], [], 2),
Bus.pt: CANParser(DBC[CP.carFingerprint][Bus.pt], [], 0) }None(None)None'__pyarmor_exit_41378__(...)''__pyarmor_exit_41378__(...)')()
    __classcell__ = staticmethod
    return staticmethod
    __classcell__ = None
    return None
    '__pyarmor_exit_41369__(...)'
    '__pyarmor_exit_41369__(...)'

return None
return None
'__pyarmor_exit_41366__(...)'
'__pyarmor_exit_41366__(...)'
