# File: changancan.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: changancan.py.1shot.das

'__pyarmor_enter_41392__(...)'
crc8_tab = [
    0,
    29,
    58,
    39,
    116,
    105,
    78,
    83,
    232,
    245,
    210,
    207,
    156,
    129,
    166,
    187,
    205,
    208,
    247,
    234,
    185,
    164,
    131,
    158,
    37,
    56,
    31,
    2,
    81,
    76,
    107,
    118,
    135,
    154,
    189,
    160,
    243,
    238,
    201,
    212,
    111,
    114,
    85,
    72,
    27,
    6,
    33,
    60,
    74,
    87,
    112,
    109,
    62,
    35,
    4,
    25,
    162,
    191,
    152,
    133,
    214,
    203,
    236,
    241,
    19,
    14,
    41,
    52,
    103,
    122,
    93,
    64,
    251,
    230,
    193,
    220,
    143,
    146,
    181,
    168,
    222,
    195,
    228,
    249,
    170,
    183,
    144,
    141,
    54,
    43,
    12,
    17,
    66,
    95,
    120,
    101,
    148,
    137,
    174,
    179,
    224,
    253,
    218,
    199,
    124,
    97,
    70,
    91,
    8,
    21,
    50,
    47,
    89,
    68,
    99,
    126,
    45,
    48,
    23,
    10,
    177,
    172,
    139,
    150,
    197,
    216,
    255,
    226,
    38,
    59,
    28,
    1,
    82,
    79,
    104,
    117,
    206,
    211,
    244,
    233,
    186,
    167,
    128,
    157,
    235,
    246,
    209,
    204,
    159,
    130,
    165,
    184,
    3,
    30,
    57,
    36,
    119,
    106,
    77,
    80,
    161,
    188,
    155,
    134,
    213,
    200,
    239,
    242,
    73,
    84,
    115,
    110,
    61,
    32,
    7,
    26,
    108,
    113,
    86,
    75,
    24,
    5,
    34,
    63,
    132,
    153,
    190,
    163,
    240,
    237,
    202,
    215,
    53,
    40,
    15,
    18,
    65,
    92,
    123,
    102,
    221,
    192,
    231,
    250,
    169,
    180,
    147,
    142,
    248,
    229,
    194,
    223,
    140,
    145,
    182,
    171,
    16,
    13,
    42,
    55,
    100,
    121,
    94,
    67,
    178,
    175,
    136,
    149,
    198,
    219,
    252,
    225,
    90,
    71,
    96,
    125,
    46,
    51,
    20,
    9,
    127,
    98,
    69,
    88,
    11,
    22,
    49,
    44,
    151,
    138,
    173,
    176,
    227,
    254,
    217,
    196]

def crc_calculate_crc8(data):
    '__pyarmor_enter_41395__(...)'
    _var_var_0 = 255
    for _var_var_1 in data:
        _var_var_0 = crc8_tab[_var_var_0 ^ _var_var_1]
    return _var_var_0 ^ 255
    None(None)
    return None
    '__pyarmor_exit_41396__(...)'
    '__pyarmor_exit_41396__(...)'


def crc16_ccitt_false(data, poly, init_val):
    '__pyarmor_enter_41398__(...)'
    _var_var_0 = init_val
    for _var_var_1 in data:
        _var_var_0 ^= _var_var_1 << 8
        for _var_var_2 in range(8):
            _var_var_0 &= 65535
    return _var_var_0
    None(None)
    return None
    '__pyarmor_exit_41399__(...)'
    '__pyarmor_exit_41399__(...)'


def create_244_command_a05(packer, accel, counter, longActive, accTrq):
    '__pyarmor_enter_41401__(...)'
# WARNING: Decompyle incomplete


def create_244_command(packer, msg, accel, counter, longActive, accTrq, vEgoRaw):
    '__pyarmor_enter_41404__(...)'
    _var_var_3 = msg.copy()
    _var_var_3.update({
        'ACC_ACCTargetAcceleration': accel,
        'ACC_CDDActive': 1 if longActive and accel < 0 else 0,
        'ACC_RollingCounter_24E': counter,
        'ACC_RollingCounter_25E': counter,
        'ACC_ACCMode': 3 if longActive else 2,
        'ACC_AccTrqReq': accTrq,
        'ACC_AccTrqReqActive': 1 if longActive and accel >= 0 else 0 })
    _var_var_4 = packer.make_can_msg('GW_244', 0, _var_var_3)[1]
    _var_var_3['ACC_CRCCheck_24E'] = crc_calculate_crc8(_var_var_4[:7])
    _var_var_3['ACC_CRCCheck_25E'] = crc_calculate_crc8(_var_var_4[8:15])
    return packer.make_can_msg('GW_244', 0, _var_var_3)
    None(None)
    return None
    '__pyarmor_exit_41405__(...)'
    '__pyarmor_exit_41405__(...)'


def create_244_command_idd(packer, msg, accel, counter, longActive, accTrq, vEgoRaw):
    '__pyarmor_enter_41407__(...)'
    _var_var_3 = msg.copy()
# WARNING: Decompyle incomplete


def create_1BA_command(packer, msg, angle, latCtrlActive, counter):
    '__pyarmor_enter_41410__(...)'
# WARNING: Decompyle incomplete


def create_17E_command(packer, msg, longActive, counter):
    '__pyarmor_enter_41413__(...)'
# WARNING: Decompyle incomplete


def create_307_command(packer, msg, counter, cruiseSpeed):
    '__pyarmor_enter_41416__(...)'
# WARNING: Decompyle incomplete


def create_31A_command(packer, msg, counter, longActive, steeringPressed):
    '__pyarmor_enter_41419__(...)'
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_41393__(...)'
'__pyarmor_exit_41393__(...)'
