# File: interface.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: interface.py.1shot.das

'__pyarmor_enter_41380__(...)'
from opendbc.car.changan.values import DBC, CarControllerParams, EPS_SCALE
from opendbc.car import structs, get_safety_config
from opendbc.car.interfaces import CarInterfaceBase
from opendbc.car.changan.carcontroller import CarController
from opendbc.car.changan.carstate import CarState
from opendbc.car.changan.radar_interface import RadarInterface
from openpilot.system.hardware import HARDWARE
from opendbc.car.changan.values import CAR, ChanganSafetyFlags
from openpilot.common.params import Params
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import padding
import base64
SteerControlType = structs.CarParams.SteerControlType

class CarInterface(CarInterfaceBase):
    '__pyarmor_enter_41383__(...)'
    CarState = CarState
    CarController = CarController
    RadarInterface = RadarInterface
    get_pid_accel_limits = (lambda CP, current_speed, cruise_speed: '__pyarmor_enter_41386__(...)'(CarControllerParams.ACCEL_MIN, CarControllerParams.ACCEL_MAX)None(None)None'__pyarmor_exit_41387__(...)''__pyarmor_exit_41387__(...)')()
    _get_params = (lambda ret, candidate, fingerprint, car_fw, experimental_longh, is_release, docs: '__pyarmor_enter_41389__(...)'ret.brand = 'changan'ret.safetyConfigs = [
get_safety_config(structs.CarParams.SafetyModel.changan)]if candidate == CAR.QIYUAN_A05:
passelif candidate == CAR.CHANGAN_Z6_IDD:
pass0.12 = ret.safetyConfigs[0], ret.safetyConfigs[0].safetyParam |= ChanganSafetyFlags.CHANGAN_Z6_FLAG.value, .safetyParamret.steerLimitTimer = 1ret.steerControlType = structs.CarParams.SteerControlType.angleret.centerToFront = ret.wheelbase * 0.44ret.enableBsm = Trueret.radarUnavailable = Trueret.openpilotLongitudinalControl = Trueret.autoResumeSng = ret.openpilotLongitudinalControlret.minEnableSpeed = -1ret.vEgoStopping = 0.25ret.vEgoStarting = 0.25ret.stoppingDecelRate = 0.3ret.minSteerSpeed = 0ret.startingState = Trueret.startAccel = 0.5ret.stopAccel = -0.5ret.longitudinalActuatorDelay = 0.3_var_var_0 = Params()_var_var_1 = _var_var_0.get('OpAuthKey')# WARNING: Decompyle incomplete
)()
    return None
    staticmethod
    return None
    '__pyarmor_exit_41384__(...)'
    '__pyarmor_exit_41384__(...)'

return None
return None
'__pyarmor_exit_41381__(...)'
'__pyarmor_exit_41381__(...)'
