# File: radar_interface.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: radar_interface.py.1shot.das

'__pyarmor_enter_41464__(...)'
from opendbc.car.interfaces import RadarInterfaceBase
from opendbc.car import Bus, structs
from opendbc.can.parser import CANParser

class RadarInterface(RadarInterfaceBase):
    '__pyarmor_enter_41467__(...)'
    
    def __init__(self, CP):
        '__pyarmor_enter_41470__(...)'
    # WARNING: Decompyle incomplete

    
    def update(self, can_strings):
        '__pyarmor_enter_41473__(...)'
    # WARNING: Decompyle incomplete

    __classcell__ = None
    return None
    __classcell__ = None
    return None
    '__pyarmor_exit_41468__(...)'
    '__pyarmor_exit_41468__(...)'

return None
return None
'__pyarmor_exit_41465__(...)'
'__pyarmor_exit_41465__(...)'
