# File: values.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: values.py.1shot.das

'__pyarmor_enter_41434__(...)'
import re
from collections import defaultdict
from dataclasses import dataclass, field
from enum import Enum, IntFlag
from opendbc.car.common.conversions import Conversions as CV
from opendbc.car import Bus, DbcDict, PlatformConfig, Platforms, CarSpecs, structs
from opendbc.car.lateral import AngleSteeringLimits
from opendbc.car.docs_definitions import CarDocs, CarParts, CarHarness
Ecu = structs.CarParams.Ecu
MIN_ACC_SPEED = 19 * CV.MPH_TO_MS
PEDAL_TRANSITION = 10 * CV.MPH_TO_MS

class CarControllerParams:
    '__pyarmor_enter_41437__(...)'
    ACCEL_MAX = 2
    ACCEL_MIN = -3.5
    STEER_STEP = 1
    STEER_MAX = 900
    STEER_ERROR_MAX = 650
    ANGLE_LIMITS: AngleSteeringLimits = AngleSteeringLimits(180, ([
        10,
        20], [
        1.4,
        0.15]), ([
        10,
        20], [
        1.4,
        0.26]))
    
    def __init__(self, CP):
        '__pyarmor_enter_41440__(...)'
        if CP.lateralTuning.which == 'torque':
            self.STEER_DELTA_UP = 15
            self.STEER_DELTA_DOWN = 25
        else:
            self.STEER_DELTA_UP = 10
            self.STEER_DELTA_DOWN = 25
        return None
        return None
        '__pyarmor_exit_41441__(...)'
        '__pyarmor_exit_41441__(...)'

    return None
    return None
    '__pyarmor_exit_41438__(...)'
    '__pyarmor_exit_41438__(...)'


class ChanganSafetyFlags(IntFlag):
    '__pyarmor_enter_41443__(...)'
    CHANGAN_Z6_FLAG = 1
    QIYUAN_A05_FLAG = 2
    CHANGAN_Z6_IDD_FLAG = 4
    return None
    return None
    '__pyarmor_exit_41444__(...)'
    '__pyarmor_exit_41444__(...)'

ChangAnCarDocs = <NODE:12>()
ChanganPlatformConfig = <NODE:12>()
QiyuanPlatformConfig = <NODE:12>()
QiyuanA07PlatformConfig = <NODE:12>()

class CAR(Platforms):
    '__pyarmor_enter_41458__(...)'
    CHANGAN_Z6 = ChanganPlatformConfig([
        ChangAnCarDocs('Changan Z6')], CarSpecs(mass = 2205, wheelbase = 2.8, steerRatio = 15, tireStiffnessFactor = 0.444))
    CHANGAN_Z6_IDD = ChanganPlatformConfig([
        ChangAnCarDocs('Changan Z6 Idd')], CarSpecs(mass = 2205, wheelbase = 2.8, steerRatio = 15, tireStiffnessFactor = 0.444))
    QIYUAN_A05 = QiyuanPlatformConfig([
        ChangAnCarDocs('Changan Qiyuan Q05')], CarSpecs(mass = 1965, wheelbase = 2.76, steerRatio = 13.9, tireStiffnessFactor = 0.444))
    QIYUAN_A07 = QiyuanA07PlatformConfig([
        ChangAnCarDocs('Changan Qiyuan Q07')], CarSpecs(mass = 2190, wheelbase = 2.76, steerRatio = 13.9, tireStiffnessFactor = 0.444))
    return None
    return None
    '__pyarmor_exit_41459__(...)'
    '__pyarmor_exit_41459__(...)'

STEER_THRESHOLD = 15
EPS_SCALE = defaultdict((lambda : 73))
DBC = CAR.create_dbc_map()
return None
dataclass
return None
'__pyarmor_exit_41435__(...)'
'__pyarmor_exit_41435__(...)'
return dataclass
